import { GoogleGenAI, Modality, Type, GenerateContentResponse } from "@google/genai";
import { ValidationResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });

/**
 * Generates an image based on a base image and a text prompt.
 * @param base64Image The base64 encoded source image.
 * @param prompt The text prompt guiding the image generation.
 * @returns A promise that resolves to the base64 encoded generated image.
 */
export const generateImage = async (base64Image: string, prompt: string): Promise<string> => {
    try {
        const response: GenerateContentResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: base64Image,
                            mimeType: 'image/jpeg',
                        },
                    },
                    {
                        text: prompt,
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        const imagePart = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
        if (imagePart?.inlineData) {
            return imagePart.inlineData.data;
        }
        
        throw new Error('No image was generated by the API.');
    } catch (error) {
        console.error('Error generating image:', error);
        throw new Error('Failed to generate image. The AI model might have refused the request due to safety policies. Please try a different photo or prompt.');
    }
};

/**
 * Validates an image based on a prompt, expecting a JSON response.
 * @param base64Image The base64 encoded image to validate.
 * @param prompt The validation prompt.
 * @returns A promise that resolves to a ValidationResult object.
 */
export const validateImage = async (base64Image: string, prompt: string): Promise<ValidationResult> => {
    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: base64Image,
                            mimeType: "image/jpeg",
                        },
                    },
                    { text: prompt },
                ],
            },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        isValid: { type: Type.BOOLEAN },
                        feedback: { type: Type.STRING },
                    },
                    required: ["isValid", "feedback"],
                },
            },
        });

        const jsonText = response.text;
        const result = JSON.parse(jsonText);
        return result;

    } catch (error) {
        console.error("Error validating image:", error);
        return {
            isValid: false,
            feedback: "Could not validate the image. The API might be temporarily unavailable. Please try again."
        };
    }
};